### ISSUE TITLE
Disabled SonarTS rules

### ISSUE THREAD

**Issue by stas-vilchik** [anvilabs/tslint-config#1]
Hi,

I'm a developer of [SonarTS](https://github.com/SonarSource/SonarTS), and I was passing by near your **tslint-config** project.

I saw you disabled two SonarTS rules [`no-dead-store`](https://github.com/SonarSource/SonarTS/blob/master/sonarts-core/docs/rules/no-dead-store.md) and [`no-identical-functions`](https://github.com/SonarSource/SonarTS/blob/master/sonarts-core/docs/rules/no-identical-functions.md) because they were generating false positives. Could you elaborate a bit more and maybe provide code samples to reproduce the problems? It would be really helpful for us, and we could fix these false positives in the next version of SonarTS.

Thank you!

**Comment by yenbekbay** [comment]
@stas-vilchik Hi! Sorry for the delayed reply.

`no-dead-store` is disabled because it doesn't work well with the usage of [rest properties](https://github.com/tc39/proposal-object-rest-spread) for "omitting" properties.
For example,
```js
const { type, ...coords } = data;
```
Here, `type` is "ommited" from the `data` object. With the `no-dead-store` rule enabled, `type` is marked as unused.
As a reference, ESLint has a [special option](https://eslint.org/docs/rules/no-unused-vars#ignorerestsiblings) with the `no-unused-vars` rule for this use case.

As for `no-identical-functions`, there really weren't any false positives per se. It was just a special use case in our codebase, where the same function was repeated a number of times and it made no sense to extract it. I'm going to enable this rule and just use `disable` comment rule flags from now on.

**Comment by stas-vilchik** [comment]
Hi @yenbekbay!

Good news! We've just [published](https://github.com/SonarSource/SonarTS/releases/tag/1.4.0-RC) a prerelease of SonarTS 1.4.0. This version fixes the false positive on `no-dead-store` with rest properties.

Could you give it a try and tell if your issues are fixed? Thanks!

**Comment by yenbekbay** [comment]
@stas-vilchik I updated the plugin and everything works perfectly. Thanks!
